### ISSUE TITLE
能支持consul吗 gozero支持把etcd换成consul

### ISSUE THREAD

**Issue by lxxwilliam** [Mikaelemmmm/gozerodtm#4]

**Comment by yedf2** [comment]
你能够帮忙给dtmdriver-gozero提pr，支持这个吗？

**Comment by Mikaelemmmm** [comment]
> 你能够帮忙给dtmdriver-gozero提pr，支持这个吗？

consul我用的不多，我先看看哈

**Comment by yedf2** [comment]
感谢，因为go-zero里面，不同的注册中心，一般用了不同的schema名称，应该是可以让dtm同时支持etcd 和consul的

**Comment by Mikaelemmmm** [comment]
已支持
